- name: main / Install epel-relase from yum
  yum:
    name: "epel-release"
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: main / Install the required packages
  package:
    name: re2c
    state: present
  become: true

- name: main / Make module dir
  file:
    path: "{{ epics_base_modules_name }}/soft/seq"
    state: directory
    owner: "{{ epics_base_owner }}"
    group: "{{ epics_base_group }}"
    mode: 0755

- name: main / Chack module exists
  stat: path={{ epics_base_modules_name }}/soft/seq/{{ epics_seq_ver }}
  register: module_exists

- block:
  - name: main / Download module src
    unarchive:
      src: "{{ epics_seq_url }}"
      dest: "{{ epics_base_modules_name }}/soft/seq"
      owner: "{{ epics_base_owner }}"
      group: "{{ epics_base_group }}"
      remote_src: True

  - name: main / Move module
    command: "mv {{ epics_base_modules_name }}/soft/seq/{{ epics_seq_unarchived_name }} {{ epics_base_modules_name }}/soft/seq/{{ epics_seq_ver }}"
  when: not module_exists.stat.exists

- name: main / Copy RELEASE.local file
  template:
    src: "RELEASE.j2"
    dest: "{{ epics_base_modules_name }}/soft/seq/{{ epics_seq_ver }}/configure/RELEASE.local"
    owner: "{{ epics_base_owner }}"
    group: "{{ epics_base_group }}"
    mode: 0664

- name: main / Make epics module
  make:
    chdir: "{{ epics_base_modules_name }}/soft/seq/{{ epics_seq_ver }}"
  environment:
    EPICS_HOST_ARCH: "{{ epics_base_epics_host_arch }}"
  become: true
  become_user: "{{ epics_base_owner }}"
