---
- name: main / Chack extension exists
  stat: 
    path: "{{ epics_base_extensions_name }}/src/{{ epics_casnooper_unarchived_name }}"
  register: extension_exists

- name: main / Download extension
  unarchive:
    src: "{{ epics_casnooper_url }}"
    dest: "{{ epics_base_extensions_name }}/src"
    owner: "{{ epics_base_owner }}"
    group: "{{ epics_base_group }}"
    remote_src: True
  when: not extension_exists.stat.exists

- name: main / Make epics extensions
  make:
    chdir: "{{ epics_base_extensions_name }}/src/{{ epics_casnooper_unarchived_name }}"
  environment:
    EPICS_HOST_ARCH: "{{ epics_base_epics_host_arch }}"
    EPICS_BASE: "{{ epics_base_base_name }}"
  become: true
  become_user: "{{ epics_base_owner }}"
