---
- name: main / Chack extension exists
  stat: 
    path: "{{ epics_base_extensions_name }}/src/{{ epics_gateway_unarchived_name }}"
  register: extension_exists

- name: main / Download extension
  unarchive:
    src: "{{ epics_gateway_url }}"
    dest: "{{ epics_base_extensions_name }}/src"
    owner: "{{ epics_base_owner }}"
    group: "{{ epics_base_group }}"
    remote_src: True
  when: not extension_exists.stat.exists

- name: main / Copy RELEASE.local file
  template:
    src: "RELEASE.j2"
    dest: "{{ epics_base_extensions_name }}/src/{{ epics_gateway_unarchived_name }}/configure/RELEASE.local"
    owner: "{{ epics_base_owner }}"
    group: "{{ epics_base_group }}"
    mode: 0664

- name: main / Make epics extensions
  make:
    chdir: "{{ epics_base_extensions_name }}/src/{{ epics_gateway_unarchived_name }}"
  environment:
    EPICS_HOST_ARCH: "{{ epics_base_epics_host_arch }}"
    EPICS_BASE: "{{ epics_base_base_name }}"
  become: true
  become_user: "{{ epics_base_owner }}"
